info:
  profile: dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: {cipher}358c56a214b76af8a087f1609eff7a1584eede15ac1cabb1c5efb48b933b2710
    driver-class-name: com.mysql.jdbc.Driver
